services:
  debt-calculator:
    image: node:18
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./src:/srv/app"
    networks:
      - nginx
    working_dir: "/srv/app"
    command: [ "yarn", "start" ]

networks:
  nginx:
    name: nginx
    external: true
