services:
  debt-calculator:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./src:/srv/app"
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    external: true
